### ISSUE TITLE
Can't install starkbank on clean python installation

### ISSUE THREAD

**Issue by thalesmello** [starkbank/sdk-python#2]
It's not possible to install v0.0.3 of the library in a clean python environment.

To reproduce with Python 2.7:

```
pip install virtualenv
python -m virtualenv venv
./venv/bin/pip install starkbank
```

Output:

```
Collecting starkbank
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/54/79/8926f2019de64d6ffdf6db3d3bfab628a109f8b38208014b21d5868d58de/starkbank-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-o7s6re50/starkbank/setup.py", line 3, in <module>
        from starkbank import __version__
      File "/tmp/pip-build-o7s6re50/starkbank/starkbank/__init__.py", line 3, in <module>
        from .user.__project import Project
      File "/tmp/pip-build-o7s6re50/starkbank/starkbank/user/__project.py", line 1, in <module>
        from .__user import User
      File "/tmp/pip-build-o7s6re50/starkbank/starkbank/user/__user.py", line 2, in <module>
        from ..utils.checks import check_private_key, check_environment
      File "/tmp/pip-build-o7s6re50/starkbank/starkbank/utils/__init__.py", line 1, in <module>
        from . import api, resource, case, checks, enum, request, rest
      File "/tmp/pip-build-o7s6re50/starkbank/starkbank/utils/rest.py", line 1, in <module>
        from requests import get, post, delete, patch
    ModuleNotFoundError: No module named 'requests'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-o7s6re50/starkbank/
```

The reason for this is that `setup.py` imports the `starkbank` after the `__version__` variable.
`pip` will execute `setup.py` in order to figure out the package dependencies to be installed,
but `starkbank` dependencies aren't installed yet, so the import will fail.

To avoid this issue it's necessary to avoid importing the package directly, like [`requests`](https://github.com/psf/requests/blob/bfb93d4b7d269a8735f1b216093e7e9a9fdc4517/setup.py#L60-L62).

**Comment by thalesmello** [comment]
Fixed by #3
