### ISSUE TITLE
Internal Import Error in v2.18

### ISSUE THREAD

**Issue by LucasCiziks** [starkbank/sdk-python#96]
Hello! Hope you guys are doing fine.

When using the latest version 2.18.0 released today, the module doesn't work. After commit #95, it seems to have a problem with the import`from .metadata.__metadata import _sub_resource as _metadata_resource
` inside the _starkbank.transfer.transfer.py_ file. This error is affecting the whole use of the sdk, since the transfer module is imported in the ___init__.py_ file.

So a simple `import starkbank` does not work, giving the following outcome:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lucas.ciziks/Projetos/StarkBank/.venv/lib/python3.10/site-packages/starkbank/__init__.py", line 21, in <module>
    from . import transfer
  File "/Users/lucas.ciziks/Projetos/StarkBank/.venv/lib/python3.10/site-packages/starkbank/transfer/__init__.py", line 1, in <module>
    from .__transfer import create, get, pdf, query, page, delete
  File "/Users/lucas.ciziks/Projetos/StarkBank/.venv/lib/python3.10/site-packages/starkbank/transfer/__transfer.py", line 4, in <module>
    from .metadata.__metadata import _sub_resource as _metadata_resource
ModuleNotFoundError: No module named 'starkbank.transfer.metadata'`

Could you guys check on that, please? Thank you in advance!

**Comment by xavier-stark** [comment]
Hi, @LucasCiziks!

Thank you for bringing the error in our repository to our attention. We have resolved your reported issue. 

If you have any questions, do not hesitate do ask!

Best,
